name: flutter_dash_example
description: A  Flutter project for draw dashes
homepage: https://huy-lv.github.io
#Migrated by George Heavenson(Github: @oti-adjei)

version: 1.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dash:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
